### ISSUE TITLE
bonjour.saml.SAMLException: org.opensaml.xml.validation.ValidationException: Signature did not validate against the credential's key

### ISSUE THREAD

**Issue by Carson-Keep-Running** [clonekim/saml-servlet#1]
Hi,
I am trying to use OKTA developer as IDP instead, I configure the properties file and set **sso.idpmetadata = classpath:/metadata/idp-okta.xml**, and then startup the application.
When I access http://localhost:8080/saml/login, it can redirect me to OKTA login page.
But when I enter username and password and then login in the OKTA login page, it will redirect to http://localhost:8080/saml/SSO and throw below exception:
`bonjour.saml.SAMLException: org.opensaml.xml.validation.ValidationException: Signature did not validate against the credential's key
	at bonjour.saml.SAMLUtil.validateSignature(SAMLUtil.java:624)
	at bonjour.saml.SAMLUtil.parseSamltoObject(SAMLUtil.java:288)
	at bonjour.saml.SamlSSO.doPost(SamlSSO.java:29)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1402)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:567)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.opensaml.xml.validation.ValidationException: Signature did not validate against the credential's key
	at org.opensaml.xml.signature.SignatureValidator.validate(SignatureValidator.java:79)
	at bonjour.saml.SAMLUtil.validateSignature(SAMLUtil.java:620)
	... 41 more
`

**Comment by clonekim** [comment]
Hello~
first of all, this library is used for general purpose also I didn't test on OKTA
but by meaning of exception.. 
I think you have SignatureValidator more than one. fixed some code, could you try and inform me?

**Comment by Carson-Keep-Running** [comment]
Hi,
Thanks for your reply.

I have pull the latest update and test again, the following exception throwed when redirect to http://localhost:8080/saml/SSO:
`bonjour.saml.SAMLException: failed to validate about response's signature!
	at bonjour.saml.SAMLUtil.lambda$validateSignature$14(SAMLUtil.java:628)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at bonjour.saml.SAMLUtil.validateSignature(SAMLUtil.java:628)
	at bonjour.saml.SAMLUtil.parseSamltoObject(SAMLUtil.java:285)
	at bonjour.saml.SamlSSO.doPost(SamlSSO.java:29)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1402)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:567)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)`

Actually I am new learner for SAML, I am not sure is any misconfigured by me that cause these exceptions.

You can use my OKTA develop account to test the issue. Below are all my updates base on your latest code:
**1. Update file: web.xml**
Update servlet/init-param/param-value to **classpath:/okta.properties** in both samlLoginServlet and samlSSOServlet

**2.  Add file: resources/metadata/idp-okta.xml**
`<?xml version="1.0" encoding="UTF-8"?>
<md:EntityDescriptor entityID="http://www.okta.com/exk8idme3i5r4s9gv5d7"
                     xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata">
    <md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <md:KeyDescriptor use="signing">
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>MIIDqDCCApCgAwIBAgIGAYaXggIEMA0GCSqGSIb3DQEBCwUAMIGUMQswCQYDVQQGEwJVUzETMBEG A1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0YTEU MBIGA1UECwwLU1NPUHJvdmlkZXIxFTATBgNVBAMMDGRldi0xNjc3NTM4MzEcMBoGCSqGSIb3DQEJ ARYNaW5mb0Bva3RhLmNvbTAeFw0yMzAyMjgxMDExMDVaFw0zMzAyMjgxMDEyMDVaMIGUMQswCQYD VQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsG A1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxFTATBgNVBAMMDGRldi0xNjc3NTM4MzEc MBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC ggEBANR2rim3EcB/7sQSepu+cOdXCwABwmCDPaSpQ+tVwrPBDqmktXVE+EErfWqxUMGQ5BZqbt7E BlttgWB5p0ntlqvzTdMHd9e9wH3lKrM5olisFjMKxwXW+2Hryk42SAGFq9uip1SHfnNOXL34St+T X/ehtHmVIeZHW01/AJemCU5iPYNvHoasViZJSpRbNpS7aGP7QinXx/QwCEhW9AIeNgkYidCaJ7xD R+MgPYq9URl9luyqc3+4PN6+3Y9t/frGinfZIQggnh/D2Ya/xOxS5jGwdC0OzuYbzGKIusAuLgYP Hj31+I5c0c6vPjCtiYqMtzbUg+Bmp0M1U/QILvV/Sh0CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA Dm5qqboVCzRXBmk70o9qM1wvYRv9lrKltnwHhFEp9hs1+rG54VT8p4PS5uWN0r9a7HEA9LAekG96 3kaINch6b/kFSM2ZKPd4RnRx8khOj8GUOzeWhLI3DMhhgZLuXyFkEGO96SwGvhHG8EewUe1W0SDc qSy2CeKVN/N/G+ZbqvduSGtzZJoguty06B7oxQPJuAtgnPeSVPkMhUTl1XV7Ca7St51kXzlZPiNu NOmPmIlJ61STr6YPp5siD3vGaUhFWFxi4NwluQ3ExwBPD1k3cj075b0GB2UA8ZO7Y11DjnHN4Tds 27tmTr5D9qEW3As9G+f0/dG6wximLRlU3zCdag==</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </md:KeyDescriptor>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
        <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://dev-16775383.okta.com/app/dev-16775383_samlservletapp_1/exk8idme3i5r4s9gv5d7/sso/saml"/>
        <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://dev-16775383.okta.com/app/dev-16775383_samlservletapp_1/exk8idme3i5r4s9gv5d7/sso/saml"/>
    </md:IDPSSODescriptor>
</md:EntityDescriptor>`

**3. Add file: resources/okta.properties**
`sso.issuerId = urn:test:saml-servlet:sp
sso.identityProviderUrl = https://dev-16775383.okta.com/app/dev-16775383_samlservletapp_1/exk8idme3i5r4s9gv5d7/sso/saml
sso.assertionConsumerServiceUrl = http://localhost:8080/saml/SSO
sso.keystore.file = classpath:/security/samlKeystore.jks
sso.keystore.alias = apollo
sso.keystore.password = nalle123
sso.idpmetadata = classpath:/metadata/idp-okta.xml`

**4. Add file: resources/security/samlKeystore.jks**
(1)This samlKeystore.jks can be obtained in https://github.com/spring-attic/spring-security-saml/tree/main/sample/src/main/resources/security
(2)This is sample JKS keystore mentioned in https://docs.spring.io/spring-security-saml/docs/current/reference/htmlsingle/#configuration-key-management-jks

I have created a test user (username: test@github.com; password: temp@123) in my OKTA develop, you can use this test account to login OKTA and then redirect to http://localhost:8080/saml/SSO.

**Comment by clonekim** [comment]
ok, by providing your idp-okta.xml
In that case you don't need samlKeystore.jks  also  property files too.
and simply modify 

SamlLogin.java
```java
 public class SamlLogin extends HttpServlet {

    SAMLUtil samlUtil = null;

    @Override
    public void init(ServletConfig config) throws ServletException {
        super.init(config);

        samlUtil = new SAMLUtil("classpath:/metadata/idp-okta.xml", "urn:test:saml-servlet:sp");
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        resp.setContentType("text/html;charset=UTF-8");

        Writer writer = resp.getWriter();
        writer.write(samlUtil.toSAMLRequestHtml(false)); //important 
        writer.flush();

        resp.setHeader("Cache-Control", "no-cache, no-store");
        resp.setHeader("Pragma", "no-cache");

    }
}
````

**Comment by Carson-Keep-Running** [comment]
Thank you at first, I have updated the SamlLogin.java but the same exception throwed still:
`bonjour.saml.SAMLException: failed to validate about response's signature!
	at bonjour.saml.SAMLUtil.lambda$validateSignature$14(SAMLUtil.java:628)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at bonjour.saml.SAMLUtil.validateSignature(SAMLUtil.java:628)
	at bonjour.saml.SAMLUtil.parseSamltoObject(SAMLUtil.java:285)
	at bonjour.saml.SamlSSO.doPost(SamlSSO.java:29)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1402)` 

I try to update the SamlSSO.java also, but it still not work.

```
public class SamlSSO extends HttpServlet {
    SAMLUtil samlUtil = null;
    @Override
    public void init(ServletConfig config) throws ServletException {
        super.init(config);
        samlUtil = new SAMLUtil("classpath:/metadata/idp-okta.xml", "urn:test:saml-servlet:sp");
    }
    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        ......
    }
}
```

**Comment by clonekim** [comment]
what' wrong? I can't figure out
I committed new branch for you, named okta-test and also there is movies in the directory named demo-movie
check out movie and please use this source only and see demo movie carefully
what you want something beyond this library is not going to work your situations

**Comment by Carson-Keep-Running** [comment]
I find out the root cause, your okta-test branch is working well, because the **sso.idpmetadata** property is not configured in the google.preperties, which means that the SamlSSO.java parse SAML response without validating the signature.

1. In SamlSSO.doPost() method, it will call samlUtil.parseSamltoObject(samlResponse) to get SAMLUtil.SAMLUserDetail (Line#29).
2. In SAMLUtil.parseSamltoObject() method, it will check if the credentials is exists or not (Line#284-285), since the **sso.idpmetadata** property is not configured, then the credentials variable is null and will not trigger the validateSignature(response) method.

I would like to know that how can I hit the validateSignature(response) method and then pass the whole workflow. How can I configure the setting?
